# configuration
dist: trusty
sudo: required
language: java
cache:
    - apt
    - $HOME/.m2

# build matrix
jdk:
    - oraclejdk8

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-setuptools 
  - sudo easy_install3 pip
  - export LC_ALL=C
  - pip3 install -U nltk
   
# run steps
install:

script:
    - cd textdb 
    - mvn test
